# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'git@gitlab.kkinternal.com:xddd/kkboxpodspecs.git'


target 'MacPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MacPlayer
  pod 'KKAudioEngineMac'

end
